FROM openjdk:8

RUN wget -q https://services.gradle.org/distributions/gradle-4.0-rc-2-bin.zip \
    && unzip gradle-4.0-rc-2-bin.zip -d /opt \
    && rm gradle-4.0-rc-2-bin.zip

ENV GRADLE_HOME /opt/gradle-4.0-rc-2
ENV PATH $PATH:/opt/gradle-4.0-rc-2/bin


